version: '3.8'

services:
  web:
    build: .
    ports:
      - "8880:8880"
    environment:
      - COUCHDB_URL=http://couchdb:5984
    depends_on:
      couchdb:
        condition: service_healthy

  couchdb:
    image: couchdb:2.3.1
    volumes:
      - ./couchdb_data:/opt/couchdb/data
    ports:
      - "5984:5984"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5984"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  couchdb_data: